import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class CodeKeyLocalizations {
  const CodeKeyLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('ru'),
    Locale('en'),
    Locale('es'),
    Locale('zh'),
  ];

  static CodeKeyLocalizations of(BuildContext context) =>
      Localizations.of<CodeKeyLocalizations>(context, CodeKeyLocalizations) ??
      const CodeKeyLocalizations(Locale('en'));

  String get languageCode => locale.languageCode;

  String t(String key, [Map<String, Object?> values = const {}]) {
    final language = _translations[locale.languageCode] ?? _translations['en']!;
    var text = language[key] ?? _translations['en']![key] ?? key;
    for (final entry in values.entries) {
      text = text.replaceAll('{${entry.key}}', '${entry.value ?? ''}');
    }
    return text;
  }

  static const LocalizationsDelegate<CodeKeyLocalizations> delegate =
      _CodeKeyLocalizationsDelegate();

  static const Map<String, Map<String, String>> _translations = {
    'ru': {
    'cameraUnavailable': 'Камера недоступна',
    'cameraOpenFailed': 'Не удалось открыть камеру',

      'appName': 'CodeKey AI',
      'connected': 'Подключено',
      'disconnected': 'Не подключено',
      'connecting': 'Подключение…',
      'responseFromLlm': 'Ответ от LLM',
      'whatChanged': 'Что сделано / Что исправлено',
      'codeToInsert': 'Код для вставки',
      'copy': 'Копировать',
      'copied': 'Код скопирован',
      'print': 'Печать',
      'printHint': 'Куда поставить курсор, будет показано после нажатия «Печать».',
      'promptHint': 'Опишите, что нужно изменить в коде…',
      'addPhoto': 'Добавить снимок',
      'send': 'Отправить',
      'ocr': 'OCR',
      'ocrQueued': 'Ожидает OCR',
      'ocrProcessing': 'Распознавание',
      'ocrDone': 'OCR готов',
      'ocrFailed': 'Ошибка OCR',
      'editOcr': 'Распознанный текст',
      'save': 'Сохранить',
      'delete': 'Удалить',
      'close': 'Закрыть',
      'settings': 'Настройки',
      'interface': 'Интерфейс',
      'interfaceLanguage': 'Язык интерфейса',
      'workstation': 'Рабочая станция',
      'operatingSystem': 'Операционная система',
      'editor': 'Редактор кода',
      'keyboardLayout': 'Раскладка клавиатуры',
      'typing': 'Печать',
      'typingSpeed': 'Скорость: {value} симв./с',
      'humanized': 'Естественный темп печати',
      'api': 'Внешний API',
      'apiProvider': 'Формат API',
      'apiBaseUrl': 'Базовый URL API',
      'apiModel': 'Модель',
      'apiKey': 'API-ключ',
      'apiTimeout': 'Тайм-аут, секунд',
      'privacy': 'Конфиденциальность',
      'corporateTerms': 'Внутренние домены и названия через запятую',
      'device': 'Устройство ESP32-S3',
      'scan': 'Найти устройства',
      'scanning': 'Поиск…',
      'connect': 'Подключить',
      'disconnect': 'Отключить',
      'setupKey': 'Ключ устройства',
      'noDevices': 'Устройства CodeKey не найдены',
      'deviceDiscoveryHint': 'ESP32 виден по Bluetooth всегда, пока к нему не подключён смартфон. Для подключения нужен индивидуальный ключ устройства.',
      'usbIdentity': 'USB-идентификация',
      'vid': 'VID (4 HEX)',
      'pid': 'PID (4 HEX)',
      'manufacturer': 'Производитель',
      'productName': 'Имя клавиатуры',
      'serialNumber': 'Серийный номер',
      'applyUsb': 'Записать в ESP32 и перезагрузить',
      'usbWarning': 'Используйте VID/PID, которыми вы вправе пользоваться. После изменения устройство переподключится к USB.',
      'saved': 'Настройки сохранены',
      'apiNotConfigured': 'Укажите URL API, модель и API-ключ в настройках.',
      'requestRequired': 'Введите запрос пользователя.',
      'codeRequired': 'Снимок не обязателен: можно отправить только текстовый запрос.',
      'processing': 'Обработка…',
      'privacyCheck': 'Проверка конфиденциальности',
      'findings': 'Найдено потенциально конфиденциальных фрагментов: {count}',
      'maskedPayload': 'Точный текст, который будет отправлен',
      'systemInstruction': 'Системная инструкция',
      'userPayload': 'Запрос и код',
      'rightsConfirm': 'Я имею право отправить этот фрагмент во внешний API',
      'sendMasked': 'Отправить проверенный текст',
      'backToEdit': 'Вернуться к редактированию',
      'noFindings': 'Явные секреты и персональные данные не обнаружены. Это не доказывает, что исходный код не является конфиденциальным.',
      'cursorPlacement': 'Куда поставить курсор',
      'operation': 'Режим вставки',
      'cursorReady': 'Я установил курсор и подготовил редактор',
      'saveAfter': 'Сохранить после печати',
      'formatAfter': 'Форматировать после печати',
      'startPrinting': 'Начать печать',
      'printing': 'Печать: {done} из {total}',
      'pause': 'Пауза',
      'resume': 'Продолжить',
      'stop': 'Остановить',
      'completed': 'Печать завершена',
      'asciiError': 'Текст содержит символы, которых нет в выбранной раскладке: {chars}',
      'deviceRequired': 'Сначала подключите CodeKey к смартфону.',
      'warnings': 'Предупреждения',
      'retry': 'Повторить',
      'newRequest': 'Новый запрос',
      'operationInsert': 'Вставить в позицию курсора',
      'operationReplaceSelection': 'Заменить выделенный текст',
      'operationReplaceFile': 'Заменить содержимое файла',
      'operationNone': 'Только рекомендация',
      'error': 'Ошибка',
      'cameraPermission': 'Для фотографирования экрана требуется доступ к камере.',
      'bluetoothPermission': 'Для подключения к CodeKey требуется доступ к Bluetooth.',
      'deviceConfigSaved': 'Конфигурация записана. ESP32 перезагрузится и USB подключится заново.',
      'hideApiKey': 'Скрыть ключ',
      'showApiKey': 'Показать ключ',
      'genericEditor': 'Обычный редактор',
      'productPreset': 'Шаблон имени',
      'custom': 'Своё имя',
      'keyboardLayouts': 'Раскладки ввода',
      'activeKeyboardLayout': 'Активная раскладка',
      'layoutHelp': 'Нажатие на иконку раскладки на главном экране сразу переключает следующий профиль. Пользовательский профиль использует выбранную базовую USB-карту клавиш.',
      'deleteLayout': 'Удалить раскладку',
      'addLayout': 'Добавить раскладку',
      'layoutName': 'Название раскладки',
      'layoutCode': 'Короткий код',
      'baseLayout': 'Базовая USB-карта клавиш',
      'add': 'Добавить',
      'deepSeekApi': 'DeepSeek API',
      'diagnostics': 'Диагностика и журналы',
      'diagnosticsHint': 'Журнал содержит этапы OCR, BLE, API и печати, но не сохраняет исходный код, запрос пользователя, API-ключи или ключ устройства. Перед отправкой журнал можно открыть и проверить.',
      'exportLogs': 'Отправить журнал для отладки',
      'clearLogs': 'Очистить журнал',
      'diagnosticsShareText': 'Диагностический журнал CodeKey для анализа ошибки.',
      'clearLogsConfirm': 'Удалить все локальные диагностические журналы CodeKey?',
      'logsCleared': 'Диагностические журналы очищены',
      'devicesFound': 'Найдено устройств: {count}',
      'layoutChanged': 'Активная раскладка: {layout}',
      'retryOcr': 'Повторить OCR',
      'ocrFailedDetails': 'Не удалось распознать изображение. Проверьте, что файл доступен, затем повторите OCR или введите текст вручную.',
      'ocrManualHint': 'Здесь можно исправить или ввести код вручную',
      'ocr_contains_failed_items': 'Удалите снимки с ошибкой OCR, повторите распознавание или введите их текст вручную.',
      'image_file_missing': 'Файл снимка больше недоступен. Удалите его и сфотографируйте экран повторно.',
      'image_file_empty': 'Файл снимка пуст. Сделайте фотографию повторно.',
      'ocr_no_text_detected': 'ML Kit не обнаружил текст. Снимите экран ближе, без бликов, или введите код вручную.',
      'mlkit_recognition_failed': 'Ошибка локального ML Kit OCR. Экспортируйте диагностический журнал для отладки.',
      'camera_permission_denied': 'Разрешите приложению доступ к камере в настройках телефона.',
      'request_required': 'Введите запрос пользователя.',
      'code_required': 'Добавьте хотя бы один снимок и проверьте OCR-текст.',
      'ocr_still_running': 'Дождитесь завершения OCR для всех снимков.',
      'api_not_configured': 'Укажите URL API, модель и API-ключ в настройках.',
      'invalid_api_url': 'Указан некорректный URL внешнего API.',
      'bluetooth_powered_off': 'Включите Bluetooth на смартфоне.',
      'bluetooth_permission_denied': 'Разрешите приложению доступ к Bluetooth.',
      'bluetooth_not_supported': 'Этот смартфон не поддерживает Bluetooth Low Energy.',
      'location_services_disabled': 'На этой версии Android включите службы геолокации для поиска BLE-устройств.',
      'bluetooth_status_unknown': 'Bluetooth ещё не готов. Повторите поиск через несколько секунд.',
      'setup_key_too_short': 'Ключ устройства должен содержать не менее 16 символов.',
      'no_code_to_print': 'Нет кода для печати.',
      'layout_code_exists': 'Раскладка с таким коротким кодом уже существует.',
      'invalid_vid_pid': 'VID и PID должны содержать ровно четыре шестнадцатеричных символа.',
      'zero_vid_pid': 'VID и PID не могут быть равны 0000.',
      'empty_usb_fields': 'Поля USB-идентификации не должны быть пустыми.',
      'usb_fields_too_long': 'Текстовые поля USB ограничены 31 символом.',
      'technicalWarnings': 'Технические предупреждения',
    },
    'en': {
    'cameraUnavailable': 'Camera unavailable',
    'cameraOpenFailed': 'Could not open camera',

      'appName': 'CodeKey AI',
      'connected': 'Connected',
      'disconnected': 'Disconnected',
      'connecting': 'Connecting…',
      'responseFromLlm': 'LLM response',
      'whatChanged': 'What was changed / fixed',
      'codeToInsert': 'Code to insert',
      'copy': 'Copy',
      'copied': 'Code copied',
      'print': 'Type',
      'printHint': 'Cursor placement will appear after you press “Type”.',
      'promptHint': 'Describe what should be changed in the code…',
      'addPhoto': 'Add screenshot',
      'send': 'Send',
      'ocr': 'OCR',
      'ocrQueued': 'Waiting for OCR',
      'ocrProcessing': 'Recognizing',
      'ocrDone': 'OCR ready',
      'ocrFailed': 'OCR failed',
      'editOcr': 'Recognized text',
      'save': 'Save',
      'delete': 'Delete',
      'close': 'Close',
      'settings': 'Settings',
      'interface': 'Interface',
      'interfaceLanguage': 'Interface language',
      'workstation': 'Workstation',
      'operatingSystem': 'Operating system',
      'editor': 'Code editor',
      'keyboardLayout': 'Keyboard layout',
      'typing': 'Typing',
      'typingSpeed': 'Speed: {value} chars/s',
      'humanized': 'Natural typing pace',
      'api': 'External API',
      'apiProvider': 'API format',
      'apiBaseUrl': 'API base URL',
      'apiModel': 'Model',
      'apiKey': 'API key',
      'apiTimeout': 'Timeout, seconds',
      'privacy': 'Privacy',
      'corporateTerms': 'Internal domains and names, comma-separated',
      'device': 'ESP32-S3 device',
      'scan': 'Find devices',
      'scanning': 'Scanning…',
      'connect': 'Connect',
      'disconnect': 'Disconnect',
      'setupKey': 'Device setup key',
      'noDevices': 'No CodeKey devices found',
      'deviceDiscoveryHint': 'ESP32 remains discoverable over Bluetooth whenever no phone is connected. The individual device setup key is required.',
      'usbIdentity': 'USB identity',
      'vid': 'VID (4 HEX)',
      'pid': 'PID (4 HEX)',
      'manufacturer': 'Manufacturer',
      'productName': 'Keyboard name',
      'serialNumber': 'Serial number',
      'applyUsb': 'Write to ESP32 and reboot',
      'usbWarning': 'Use only VID/PID values you are authorized to use. The USB device will reconnect after a change.',
      'saved': 'Settings saved',
      'apiNotConfigured': 'Set the API URL, model and API key in Settings.',
      'requestRequired': 'Enter a user request.',
      'codeRequired': 'A screenshot is optional: you can send a text-only request.',
      'processing': 'Processing…',
      'privacyCheck': 'Privacy check',
      'findings': 'Potentially confidential fragments found: {count}',
      'maskedPayload': 'Exact text that will be sent',
      'systemInstruction': 'System instruction',
      'userPayload': 'Request and code',
      'rightsConfirm': 'I am authorized to send this fragment to an external API',
      'sendMasked': 'Send reviewed text',
      'backToEdit': 'Return to editing',
      'noFindings': 'No obvious secrets or personal data were detected. This does not prove that the source code is non-confidential.',
      'cursorPlacement': 'Where to place the cursor',
      'operation': 'Insertion mode',
      'cursorReady': 'I placed the cursor and prepared the editor',
      'saveAfter': 'Save after typing',
      'formatAfter': 'Format after typing',
      'startPrinting': 'Start typing',
      'printing': 'Typing: {done} of {total}',
      'pause': 'Pause',
      'resume': 'Resume',
      'stop': 'Stop',
      'completed': 'Typing completed',
      'asciiError': 'The text contains characters unavailable in the selected layout: {chars}',
      'deviceRequired': 'Connect CodeKey to the phone first.',
      'warnings': 'Warnings',
      'retry': 'Retry',
      'newRequest': 'New request',
      'operationInsert': 'Insert at cursor',
      'operationReplaceSelection': 'Replace selected text',
      'operationReplaceFile': 'Replace file contents',
      'operationNone': 'Recommendation only',
      'error': 'Error',
      'cameraPermission': 'Camera access is required to photograph the screen.',
      'bluetoothPermission': 'Bluetooth access is required to connect CodeKey.',
      'deviceConfigSaved': 'Configuration saved. ESP32 will reboot and reconnect over USB.',
      'hideApiKey': 'Hide key',
      'showApiKey': 'Show key',
      'genericEditor': 'Generic editor',
      'productPreset': 'Name preset',
      'custom': 'Custom name',
      'keyboardLayouts': 'Input layouts',
      'activeKeyboardLayout': 'Active layout',
      'layoutHelp': 'Tapping the layout icon on the home screen immediately selects the next profile. A custom profile uses the selected base USB key map.',
      'deleteLayout': 'Delete layout',
      'addLayout': 'Add layout',
      'layoutName': 'Layout name',
      'layoutCode': 'Short code',
      'baseLayout': 'Base USB key map',
      'add': 'Add',
      'deepSeekApi': 'DeepSeek API',
      'diagnostics': 'Diagnostics and logs',
      'diagnosticsHint': 'The log records OCR, BLE, API and typing stages, but does not store source code, the user request, API keys or the device key. You can review it before sharing.',
      'exportLogs': 'Share log for debugging',
      'clearLogs': 'Clear logs',
      'diagnosticsShareText': 'CodeKey diagnostic log for error analysis.',
      'clearLogsConfirm': 'Delete all local CodeKey diagnostic logs?',
      'logsCleared': 'Diagnostic logs cleared',
      'devicesFound': 'Devices found: {count}',
      'layoutChanged': 'Active layout: {layout}',
      'retryOcr': 'Retry OCR',
      'ocrFailedDetails': 'The image could not be recognized. Check that the file is available, then retry OCR or enter the text manually.',
      'ocrManualHint': 'Correct or enter the code manually here',
      'ocr_contains_failed_items': 'Remove screenshots with OCR errors, retry recognition, or enter their text manually.',
      'image_file_missing': 'The screenshot file is no longer available. Remove it and photograph the screen again.',
      'image_file_empty': 'The screenshot file is empty. Take the photo again.',
      'ocr_no_text_detected': 'ML Kit did not detect text. Photograph the screen closer and without glare, or enter the code manually.',
      'mlkit_recognition_failed': 'Local ML Kit OCR failed. Export the diagnostic log for debugging.',
      'camera_permission_denied': 'Allow camera access in the phone settings.',
      'request_required': 'Enter a user request.',
      'code_required': 'Add at least one screenshot and review its OCR text.',
      'ocr_still_running': 'Wait until OCR finishes for every screenshot.',
      'api_not_configured': 'Set the API URL, model and API key in Settings.',
      'invalid_api_url': 'The external API URL is invalid.',
      'bluetooth_powered_off': 'Turn on Bluetooth on the phone.',
      'bluetooth_permission_denied': 'Allow the app to use Bluetooth.',
      'bluetooth_not_supported': 'This phone does not support Bluetooth Low Energy.',
      'location_services_disabled': 'On this Android version, enable location services to scan for BLE devices.',
      'bluetooth_status_unknown': 'Bluetooth is not ready yet. Retry in a few seconds.',
      'setup_key_too_short': 'The device key must contain at least 16 characters.',
      'no_code_to_print': 'There is no code to type.',
      'layout_code_exists': 'A layout with this short code already exists.',
      'invalid_vid_pid': 'VID and PID must contain exactly four hexadecimal characters.',
      'zero_vid_pid': 'VID and PID cannot be 0000.',
      'empty_usb_fields': 'USB identity fields must not be empty.',
      'usb_fields_too_long': 'USB text fields are limited to 31 characters.',
      'technicalWarnings': 'Technical warnings',
    },
    'es': {
    'cameraUnavailable': 'Cámara no disponible',
    'cameraOpenFailed': 'No se pudo abrir la cámara',

      'appName': 'CodeKey AI',
      'connected': 'Conectado',
      'disconnected': 'Sin conexión',
      'connecting': 'Conectando…',
      'responseFromLlm': 'Respuesta de la LLM',
      'whatChanged': 'Qué se cambió / corrigió',
      'codeToInsert': 'Código para insertar',
      'copy': 'Copiar',
      'copied': 'Código copiado',
      'print': 'Escribir',
      'printHint': 'La posición del cursor aparecerá después de pulsar «Escribir».',
      'promptHint': 'Describa qué debe cambiarse en el código…',
      'addPhoto': 'Añadir captura',
      'send': 'Enviar',
      'ocr': 'OCR',
      'ocrQueued': 'Esperando OCR',
      'ocrProcessing': 'Reconociendo',
      'ocrDone': 'OCR listo',
      'ocrFailed': 'Error de OCR',
      'editOcr': 'Texto reconocido',
      'save': 'Guardar',
      'delete': 'Eliminar',
      'close': 'Cerrar',
      'settings': 'Ajustes',
      'interface': 'Interfaz',
      'interfaceLanguage': 'Idioma de la interfaz',
      'workstation': 'Estación de trabajo',
      'operatingSystem': 'Sistema operativo',
      'editor': 'Editor de código',
      'keyboardLayout': 'Distribución del teclado',
      'typing': 'Escritura',
      'typingSpeed': 'Velocidad: {value} car./s',
      'humanized': 'Ritmo de escritura natural',
      'api': 'API externa',
      'apiProvider': 'Formato de API',
      'apiBaseUrl': 'URL base de la API',
      'apiModel': 'Modelo',
      'apiKey': 'Clave de API',
      'apiTimeout': 'Tiempo de espera, segundos',
      'privacy': 'Privacidad',
      'corporateTerms': 'Dominios y nombres internos separados por comas',
      'device': 'Dispositivo ESP32-S3',
      'scan': 'Buscar dispositivos',
      'scanning': 'Buscando…',
      'connect': 'Conectar',
      'disconnect': 'Desconectar',
      'setupKey': 'Clave del dispositivo',
      'noDevices': 'No se encontraron dispositivos CodeKey',
      'deviceDiscoveryHint': 'El ESP32 permanece visible por Bluetooth mientras no haya un teléfono conectado. Se requiere la clave individual del dispositivo.',
      'usbIdentity': 'Identidad USB',
      'vid': 'VID (4 HEX)',
      'pid': 'PID (4 HEX)',
      'manufacturer': 'Fabricante',
      'productName': 'Nombre del teclado',
      'serialNumber': 'Número de serie',
      'applyUsb': 'Guardar en ESP32 y reiniciar',
      'usbWarning': 'Use solo VID/PID que esté autorizado a utilizar. El dispositivo USB se reconectará.',
      'saved': 'Ajustes guardados',
      'apiNotConfigured': 'Configure la URL, el modelo y la clave de API.',
      'requestRequired': 'Introduzca una solicitud.',
      'codeRequired': 'Añada al menos una captura y revise el texto OCR.',
      'processing': 'Procesando…',
      'privacyCheck': 'Comprobación de privacidad',
      'findings': 'Fragmentos potencialmente confidenciales: {count}',
      'maskedPayload': 'Texto exacto que se enviará',
      'systemInstruction': 'Instrucción del sistema',
      'userPayload': 'Solicitud y código',
      'rightsConfirm': 'Tengo autorización para enviar este fragmento a una API externa',
      'sendMasked': 'Enviar texto revisado',
      'backToEdit': 'Volver a editar',
      'noFindings': 'No se detectaron secretos ni datos personales evidentes. Esto no demuestra que el código no sea confidencial.',
      'cursorPlacement': 'Dónde colocar el cursor',
      'operation': 'Modo de inserción',
      'cursorReady': 'He colocado el cursor y preparado el editor',
      'saveAfter': 'Guardar después de escribir',
      'formatAfter': 'Formatear después de escribir',
      'startPrinting': 'Empezar a escribir',
      'printing': 'Escribiendo: {done} de {total}',
      'pause': 'Pausa',
      'resume': 'Continuar',
      'stop': 'Detener',
      'completed': 'Escritura terminada',
      'asciiError': 'El texto contiene caracteres no disponibles en la distribución elegida: {chars}',
      'deviceRequired': 'Conecte primero CodeKey al teléfono.',
      'warnings': 'Advertencias',
      'retry': 'Reintentar',
      'newRequest': 'Nueva solicitud',
      'operationInsert': 'Insertar en el cursor',
      'operationReplaceSelection': 'Reemplazar el texto seleccionado',
      'operationReplaceFile': 'Reemplazar el contenido del archivo',
      'operationNone': 'Solo recomendación',
      'error': 'Error',
      'cameraPermission': 'Se requiere acceso a la cámara.',
      'bluetoothPermission': 'Se requiere acceso a Bluetooth.',
      'deviceConfigSaved': 'Configuración guardada. ESP32 se reiniciará y USB se reconectará.',
      'hideApiKey': 'Ocultar clave',
      'showApiKey': 'Mostrar clave',
      'genericEditor': 'Editor genérico',
      'productPreset': 'Plantilla de nombre',
      'custom': 'Nombre propio',
      'keyboardLayouts': 'Distribuciones de entrada',
      'activeKeyboardLayout': 'Distribución activa',
      'layoutHelp': 'Al tocar el icono de distribución en la pantalla principal se selecciona inmediatamente el siguiente perfil. Un perfil personalizado usa el mapa USB base elegido.',
      'deleteLayout': 'Eliminar distribución',
      'addLayout': 'Añadir distribución',
      'layoutName': 'Nombre de la distribución',
      'layoutCode': 'Código corto',
      'baseLayout': 'Mapa base de teclas USB',
      'add': 'Añadir',
      'deepSeekApi': 'API de DeepSeek',
      'diagnostics': 'Diagnóstico y registros',
      'diagnosticsHint': 'El registro guarda las etapas de OCR, BLE, API y escritura, pero no almacena el código fuente, la solicitud, las claves API ni la clave del dispositivo. Puede revisarlo antes de compartirlo.',
      'exportLogs': 'Compartir registro para depuración',
      'clearLogs': 'Borrar registros',
      'diagnosticsShareText': 'Registro de diagnóstico de CodeKey para analizar el error.',
      'clearLogsConfirm': '¿Eliminar todos los registros de diagnóstico locales de CodeKey?',
      'logsCleared': 'Registros de diagnóstico borrados',
      'devicesFound': 'Dispositivos encontrados: {count}',
      'layoutChanged': 'Distribución activa: {layout}',
      'retryOcr': 'Reintentar OCR',
      'ocrFailedDetails': 'No se pudo reconocer la imagen. Compruebe que el archivo esté disponible y vuelva a intentar el OCR o introduzca el texto manualmente.',
      'ocrManualHint': 'Corrija o introduzca aquí el código manualmente',
      'ocr_contains_failed_items': 'Elimine las capturas con errores OCR, vuelva a reconocerlas o introduzca su texto manualmente.',
      'image_file_missing': 'El archivo de captura ya no está disponible. Elimínelo y fotografíe la pantalla de nuevo.',
      'image_file_empty': 'El archivo de captura está vacío. Tome la foto de nuevo.',
      'ocr_no_text_detected': 'ML Kit no detectó texto. Fotografíe la pantalla más cerca y sin reflejos, o introduzca el código manualmente.',
      'mlkit_recognition_failed': 'Falló el OCR local de ML Kit. Exporte el registro de diagnóstico para depurarlo.',
      'camera_permission_denied': 'Permita el acceso a la cámara en los ajustes del teléfono.',
      'request_required': 'Introduzca una solicitud.',
      'code_required': 'Añada al menos una captura y revise el texto OCR.',
      'ocr_still_running': 'Espere a que finalice el OCR de todas las capturas.',
      'api_not_configured': 'Configure la URL, el modelo y la clave de API.',
      'invalid_api_url': 'La URL de la API externa no es válida.',
      'bluetooth_powered_off': 'Active Bluetooth en el teléfono.',
      'bluetooth_permission_denied': 'Permita que la aplicación use Bluetooth.',
      'bluetooth_not_supported': 'Este teléfono no admite Bluetooth Low Energy.',
      'location_services_disabled': 'En esta versión de Android, active la ubicación para buscar dispositivos BLE.',
      'bluetooth_status_unknown': 'Bluetooth aún no está listo. Inténtelo de nuevo en unos segundos.',
      'setup_key_too_short': 'La clave del dispositivo debe tener al menos 16 caracteres.',
      'no_code_to_print': 'No hay código para escribir.',
      'layout_code_exists': 'Ya existe una distribución con ese código corto.',
      'invalid_vid_pid': 'VID y PID deben tener exactamente cuatro caracteres hexadecimales.',
      'zero_vid_pid': 'VID y PID no pueden ser 0000.',
      'empty_usb_fields': 'Los campos de identidad USB no pueden estar vacíos.',
      'usb_fields_too_long': 'Los campos de texto USB están limitados a 31 caracteres.',
      'technicalWarnings': 'Advertencias técnicas',
    },
    'zh': {
    'cameraUnavailable': '相机不可用',
    'cameraOpenFailed': '无法打开相机',

      'appName': 'CodeKey AI',
      'connected': '已连接',
      'disconnected': '未连接',
      'connecting': '连接中…',
      'responseFromLlm': 'LLM 回复',
      'whatChanged': '已完成 / 已修复',
      'codeToInsert': '待输入代码',
      'copy': '复制',
      'copied': '代码已复制',
      'print': '输入',
      'printHint': '点击“输入”后才会显示光标放置说明。',
      'promptHint': '请说明需要怎样修改代码…',
      'addPhoto': '添加截图',
      'send': '发送',
      'ocr': 'OCR',
      'ocrQueued': '等待 OCR',
      'ocrProcessing': '正在识别',
      'ocrDone': 'OCR 完成',
      'ocrFailed': 'OCR 失败',
      'editOcr': '识别文本',
      'save': '保存',
      'delete': '删除',
      'close': '关闭',
      'settings': '设置',
      'interface': '界面',
      'interfaceLanguage': '界面语言',
      'workstation': '工作站',
      'operatingSystem': '操作系统',
      'editor': '代码编辑器',
      'keyboardLayout': '键盘布局',
      'typing': '输入',
      'typingSpeed': '速度：{value} 字符/秒',
      'humanized': '自然输入节奏',
      'api': '外部 API',
      'apiProvider': 'API 格式',
      'apiBaseUrl': 'API 基础地址',
      'apiModel': '模型',
      'apiKey': 'API 密钥',
      'apiTimeout': '超时（秒）',
      'privacy': '隐私',
      'corporateTerms': '内部域名和名称，用逗号分隔',
      'device': 'ESP32-S3 设备',
      'scan': '查找设备',
      'scanning': '正在查找…',
      'connect': '连接',
      'disconnect': '断开',
      'setupKey': '设备密钥',
      'noDevices': '未找到 CodeKey 设备',
      'deviceDiscoveryHint': '未连接手机时，ESP32 会一直通过蓝牙保持可发现状态。连接时需要设备专用密钥。',
      'usbIdentity': 'USB 标识',
      'vid': 'VID（4 位十六进制）',
      'pid': 'PID（4 位十六进制）',
      'manufacturer': '制造商',
      'productName': '键盘名称',
      'serialNumber': '序列号',
      'applyUsb': '写入 ESP32 并重启',
      'usbWarning': '仅使用您有权使用的 VID/PID。修改后 USB 设备会重新连接。',
      'saved': '设置已保存',
      'apiNotConfigured': '请在设置中填写 API 地址、模型和密钥。',
      'requestRequired': '请输入用户请求。',
      'codeRequired': '请至少添加一张截图并检查 OCR 文本。',
      'processing': '处理中…',
      'privacyCheck': '隐私检查',
      'findings': '发现可能的机密片段：{count}',
      'maskedPayload': '将要发送的确切文本',
      'systemInstruction': '系统指令',
      'userPayload': '请求和代码',
      'rightsConfirm': '我有权将此片段发送到外部 API',
      'sendMasked': '发送已检查文本',
      'backToEdit': '返回编辑',
      'noFindings': '未检测到明显的密钥或个人数据，但这不能证明源代码不属于机密信息。',
      'cursorPlacement': '光标放置位置',
      'operation': '插入模式',
      'cursorReady': '我已放置光标并准备好编辑器',
      'saveAfter': '输入后保存',
      'formatAfter': '输入后格式化',
      'startPrinting': '开始输入',
      'printing': '输入中：{done}/{total}',
      'pause': '暂停',
      'resume': '继续',
      'stop': '停止',
      'completed': '输入完成',
      'asciiError': '文本包含当前键盘布局无法输入的字符：{chars}',
      'deviceRequired': '请先将 CodeKey 连接到手机。',
      'warnings': '警告',
      'retry': '重试',
      'newRequest': '新请求',
      'operationInsert': '在光标处插入',
      'operationReplaceSelection': '替换选中文本',
      'operationReplaceFile': '替换文件内容',
      'operationNone': '仅提供建议',
      'error': '错误',
      'cameraPermission': '拍摄屏幕需要相机权限。',
      'bluetoothPermission': '连接 CodeKey 需要蓝牙权限。',
      'deviceConfigSaved': '配置已保存。ESP32 将重启并重新连接 USB。',
      'hideApiKey': '隐藏密钥',
      'showApiKey': '显示密钥',
      'genericEditor': '通用编辑器',
      'productPreset': '名称模板',
      'custom': '自定义名称',
      'keyboardLayouts': '输入布局',
      'activeKeyboardLayout': '当前布局',
      'layoutHelp': '点击主屏幕上的布局图标会立即选择下一个配置。自定义配置使用所选的基础 USB 键位映射。',
      'deleteLayout': '删除布局',
      'addLayout': '添加布局',
      'layoutName': '布局名称',
      'layoutCode': '短代码',
      'baseLayout': '基础 USB 键位映射',
      'add': '添加',
      'deepSeekApi': 'DeepSeek API',
      'diagnostics': '诊断与日志',
      'diagnosticsHint': '日志记录 OCR、BLE、API 和输入阶段，但不会保存源代码、用户请求、API 密钥或设备密钥。分享前可以先检查文件。',
      'exportLogs': '分享日志以便调试',
      'clearLogs': '清除日志',
      'diagnosticsShareText': '用于分析错误的 CodeKey 诊断日志。',
      'clearLogsConfirm': '删除所有本地 CodeKey 诊断日志吗？',
      'logsCleared': '诊断日志已清除',
      'devicesFound': '找到设备：{count}',
      'layoutChanged': '当前布局：{layout}',
      'retryOcr': '重试 OCR',
      'ocrFailedDetails': '无法识别图像。请确认文件仍可访问，然后重试 OCR 或手动输入文本。',
      'ocrManualHint': '可在此修正或手动输入代码',
      'ocr_contains_failed_items': '请删除 OCR 失败的截图、重试识别，或手动输入其文本。',
      'image_file_missing': '截图文件已不可用。请删除并重新拍摄屏幕。',
      'image_file_empty': '截图文件为空，请重新拍摄。',
      'ocr_no_text_detected': 'ML Kit 未检测到文本。请靠近屏幕、避免反光重新拍摄，或手动输入代码。',
      'mlkit_recognition_failed': '本地 ML Kit OCR 失败。请导出诊断日志以便调试。',
      'camera_permission_denied': '请在手机设置中允许相机权限。',
      'request_required': '请输入用户请求。',
      'code_required': '请至少添加一张截图并检查 OCR 文本。',
      'ocr_still_running': '请等待所有截图完成 OCR。',
      'api_not_configured': '请在设置中填写 API 地址、模型和密钥。',
      'invalid_api_url': '外部 API 地址无效。',
      'bluetooth_powered_off': '请打开手机蓝牙。',
      'bluetooth_permission_denied': '请允许应用使用蓝牙。',
      'bluetooth_not_supported': '此手机不支持低功耗蓝牙。',
      'location_services_disabled': '在此 Android 版本上，请开启位置服务以扫描 BLE 设备。',
      'bluetooth_status_unknown': '蓝牙尚未就绪，请几秒后重试。',
      'setup_key_too_short': '设备密钥至少需要 16 个字符。',
      'no_code_to_print': '没有可输入的代码。',
      'layout_code_exists': '已存在相同短代码的布局。',
      'invalid_vid_pid': 'VID 和 PID 必须正好包含四个十六进制字符。',
      'zero_vid_pid': 'VID 和 PID 不能为 0000。',
      'empty_usb_fields': 'USB 标识字段不能为空。',
      'usb_fields_too_long': 'USB 文本字段最多 31 个字符。',
      'technicalWarnings': '技术警告',
    },
  };
}

class _CodeKeyLocalizationsDelegate
    extends LocalizationsDelegate<CodeKeyLocalizations> {
  const _CodeKeyLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      CodeKeyLocalizations.supportedLocales
          .any((supported) => supported.languageCode == locale.languageCode);

  @override
  Future<CodeKeyLocalizations> load(Locale locale) =>
      SynchronousFuture(CodeKeyLocalizations(locale));

  @override
  bool shouldReload(_CodeKeyLocalizationsDelegate old) => false;
}

extension CodeKeyStringsContext on BuildContext {
  CodeKeyLocalizations get strings => CodeKeyLocalizations.of(this);
}
