import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class CodeKeyLocalizations {
  const CodeKeyLocalizations(this.locale);

  final Locale locale;

  static const supportedLocales = <Locale>[
    Locale('ru'),
    Locale('en'),
    Locale('es'),
    Locale('zh'),
  ];

  static CodeKeyLocalizations of(BuildContext context) =>
      Localizations.of<CodeKeyLocalizations>(context, CodeKeyLocalizations) ??
      const CodeKeyLocalizations(Locale('en'));

  String get languageCode => locale.languageCode;

  String t(String key, [Map<String, Object?> values = const {}]) {
    final language = _translations[locale.languageCode] ?? _translations['en']!;
    var text = language[key] ?? _translations['en']![key] ?? key;
    for (final entry in values.entries) {
      text = text.replaceAll('{${entry.key}}', '${entry.value ?? ''}');
    }
    return text;
  }

  static const LocalizationsDelegate<CodeKeyLocalizations> delegate =
      _CodeKeyLocalizationsDelegate();

  static const Map<String, Map<String, String>> _translations = {
    'ru': {
      'appName': 'CodeKey AI',
      'connected': 'Подключено',
      'disconnected': 'Не подключено',
      'connecting': 'Подключение…',
      'responseFromLlm': 'Ответ от LLM',
      'whatChanged': 'Что сделано / Что исправлено',
      'codeToInsert': 'Код для вставки',
      'copy': 'Копировать',
      'copied': 'Код скопирован',
      'print': 'Печать',
      'printHint': 'Куда поставить курсор, будет показано после нажатия «Печать».',
      'promptHint': 'Опишите, что нужно изменить в коде…',
      'addPhoto': 'Добавить снимок',
      'send': 'Отправить',
      'ocr': 'OCR',
      'ocrQueued': 'Ожидает OCR',
      'ocrProcessing': 'Распознавание',
      'ocrDone': 'OCR готов',
      'ocrFailed': 'Ошибка OCR',
      'editOcr': 'Распознанный текст',
      'save': 'Сохранить',
      'delete': 'Удалить',
      'close': 'Закрыть',
      'settings': 'Настройки',
      'interface': 'Интерфейс',
      'interfaceLanguage': 'Язык интерфейса',
      'workstation': 'Рабочая станция',
      'operatingSystem': 'Операционная система',
      'editor': 'Редактор кода',
      'keyboardLayout': 'Раскладка клавиатуры',
      'typing': 'Печать',
      'typingSpeed': 'Скорость: {value} симв./с',
      'humanized': 'Естественный темп печати',
      'api': 'Внешний API',
      'apiProvider': 'Формат API',
      'apiBaseUrl': 'Базовый URL API',
      'apiModel': 'Модель',
      'apiKey': 'API-ключ',
      'apiTimeout': 'Тайм-аут, секунд',
      'privacy': 'Конфиденциальность',
      'corporateTerms': 'Внутренние домены и названия через запятую',
      'device': 'Устройство ESP32-S3',
      'scan': 'Найти устройства',
      'scanning': 'Поиск…',
      'connect': 'Подключить',
      'disconnect': 'Отключить',
      'setupKey': 'Ключ устройства',
      'noDevices': 'Устройства CodeKey не найдены',
      'deviceDiscoveryHint': 'ESP32 виден по Bluetooth всегда, пока к нему не подключён смартфон. Для подключения нужен индивидуальный ключ устройства.',
      'usbIdentity': 'USB-идентификация',
      'vid': 'VID (4 HEX)',
      'pid': 'PID (4 HEX)',
      'manufacturer': 'Производитель',
      'productName': 'Имя клавиатуры',
      'serialNumber': 'Серийный номер',
      'applyUsb': 'Записать в ESP32 и перезагрузить',
      'usbWarning': 'Используйте VID/PID, которыми вы вправе пользоваться. После изменения устройство переподключится к USB.',
      'saved': 'Настройки сохранены',
      'apiNotConfigured': 'Укажите URL API, модель и API-ключ в настройках.',
      'requestRequired': 'Введите запрос пользователя.',
      'codeRequired': 'Добавьте хотя бы один снимок и проверьте OCR-текст.',
      'processing': 'Обработка…',
      'privacyCheck': 'Проверка конфиденциальности',
      'findings': 'Найдено потенциально конфиденциальных фрагментов: {count}',
      'maskedPayload': 'Точный текст, который будет отправлен',
      'systemInstruction': 'Системная инструкция',
      'userPayload': 'Запрос и код',
      'rightsConfirm': 'Я имею право отправить этот фрагмент во внешний API',
      'sendMasked': 'Отправить проверенный текст',
      'backToEdit': 'Вернуться к редактированию',
      'noFindings': 'Явные секреты и персональные данные не обнаружены. Это не доказывает, что исходный код не является конфиденциальным.',
      'cursorPlacement': 'Куда поставить курсор',
      'operation': 'Режим вставки',
      'cursorReady': 'Я установил курсор и подготовил редактор',
      'saveAfter': 'Сохранить после печати',
      'formatAfter': 'Форматировать после печати',
      'startPrinting': 'Начать печать',
      'printing': 'Печать: {done} из {total}',
      'pause': 'Пауза',
      'resume': 'Продолжить',
      'stop': 'Остановить',
      'completed': 'Печать завершена',
      'asciiError': 'Текст содержит символы, которых нет в выбранной раскладке: {chars}',
      'deviceRequired': 'Сначала подключите CodeKey к смартфону.',
      'warnings': 'Предупреждения',
      'retry': 'Повторить',
      'newRequest': 'Новый запрос',
      'operationInsert': 'Вставить в позицию курсора',
      'operationReplaceSelection': 'Заменить выделенный текст',
      'operationReplaceFile': 'Заменить содержимое файла',
      'operationNone': 'Только рекомендация',
      'error': 'Ошибка',
      'cameraPermission': 'Для фотографирования экрана требуется доступ к камере.',
      'bluetoothPermission': 'Для подключения к CodeKey требуется доступ к Bluetooth.',
      'deviceConfigSaved': 'Конфигурация записана. ESP32 перезагрузится и USB подключится заново.',
      'hideApiKey': 'Скрыть ключ',
      'showApiKey': 'Показать ключ',
      'genericEditor': 'Обычный редактор',
      'productPreset': 'Шаблон имени',
      'custom': 'Своё имя',
      'technicalWarnings': 'Технические предупреждения',
    },
    'en': {
      'appName': 'CodeKey AI',
      'connected': 'Connected',
      'disconnected': 'Disconnected',
      'connecting': 'Connecting…',
      'responseFromLlm': 'LLM response',
      'whatChanged': 'What was changed / fixed',
      'codeToInsert': 'Code to insert',
      'copy': 'Copy',
      'copied': 'Code copied',
      'print': 'Type',
      'printHint': 'Cursor placement will appear after you press “Type”.',
      'promptHint': 'Describe what should be changed in the code…',
      'addPhoto': 'Add screenshot',
      'send': 'Send',
      'ocr': 'OCR',
      'ocrQueued': 'Waiting for OCR',
      'ocrProcessing': 'Recognizing',
      'ocrDone': 'OCR ready',
      'ocrFailed': 'OCR failed',
      'editOcr': 'Recognized text',
      'save': 'Save',
      'delete': 'Delete',
      'close': 'Close',
      'settings': 'Settings',
      'interface': 'Interface',
      'interfaceLanguage': 'Interface language',
      'workstation': 'Workstation',
      'operatingSystem': 'Operating system',
      'editor': 'Code editor',
      'keyboardLayout': 'Keyboard layout',
      'typing': 'Typing',
      'typingSpeed': 'Speed: {value} chars/s',
      'humanized': 'Natural typing pace',
      'api': 'External API',
      'apiProvider': 'API format',
      'apiBaseUrl': 'API base URL',
      'apiModel': 'Model',
      'apiKey': 'API key',
      'apiTimeout': 'Timeout, seconds',
      'privacy': 'Privacy',
      'corporateTerms': 'Internal domains and names, comma-separated',
      'device': 'ESP32-S3 device',
      'scan': 'Find devices',
      'scanning': 'Scanning…',
      'connect': 'Connect',
      'disconnect': 'Disconnect',
      'setupKey': 'Device setup key',
      'noDevices': 'No CodeKey devices found',
      'deviceDiscoveryHint': 'ESP32 remains discoverable over Bluetooth whenever no phone is connected. The individual device setup key is required.',
      'usbIdentity': 'USB identity',
      'vid': 'VID (4 HEX)',
      'pid': 'PID (4 HEX)',
      'manufacturer': 'Manufacturer',
      'productName': 'Keyboard name',
      'serialNumber': 'Serial number',
      'applyUsb': 'Write to ESP32 and reboot',
      'usbWarning': 'Use only VID/PID values you are authorized to use. The USB device will reconnect after a change.',
      'saved': 'Settings saved',
      'apiNotConfigured': 'Set the API URL, model and API key in Settings.',
      'requestRequired': 'Enter a user request.',
      'codeRequired': 'Add at least one screenshot and review its OCR text.',
      'processing': 'Processing…',
      'privacyCheck': 'Privacy check',
      'findings': 'Potentially confidential fragments found: {count}',
      'maskedPayload': 'Exact text that will be sent',
      'systemInstruction': 'System instruction',
      'userPayload': 'Request and code',
      'rightsConfirm': 'I am authorized to send this fragment to an external API',
      'sendMasked': 'Send reviewed text',
      'backToEdit': 'Return to editing',
      'noFindings': 'No obvious secrets or personal data were detected. This does not prove that the source code is non-confidential.',
      'cursorPlacement': 'Where to place the cursor',
      'operation': 'Insertion mode',
      'cursorReady': 'I placed the cursor and prepared the editor',
      'saveAfter': 'Save after typing',
      'formatAfter': 'Format after typing',
      'startPrinting': 'Start typing',
      'printing': 'Typing: {done} of {total}',
      'pause': 'Pause',
      'resume': 'Resume',
      'stop': 'Stop',
      'completed': 'Typing completed',
      'asciiError': 'The text contains characters unavailable in the selected layout: {chars}',
      'deviceRequired': 'Connect CodeKey to the phone first.',
      'warnings': 'Warnings',
      'retry': 'Retry',
      'newRequest': 'New request',
      'operationInsert': 'Insert at cursor',
      'operationReplaceSelection': 'Replace selected text',
      'operationReplaceFile': 'Replace file contents',
      'operationNone': 'Recommendation only',
      'error': 'Error',
      'cameraPermission': 'Camera access is required to photograph the screen.',
      'bluetoothPermission': 'Bluetooth access is required to connect CodeKey.',
      'deviceConfigSaved': 'Configuration saved. ESP32 will reboot and reconnect over USB.',
      'hideApiKey': 'Hide key',
      'showApiKey': 'Show key',
      'genericEditor': 'Generic editor',
      'productPreset': 'Name preset',
      'custom': 'Custom name',
      'technicalWarnings': 'Technical warnings',
    },
    'es': {
      'appName': 'CodeKey AI',
      'connected': 'Conectado',
      'disconnected': 'Sin conexión',
      'connecting': 'Conectando…',
      'responseFromLlm': 'Respuesta de la LLM',
      'whatChanged': 'Qué se cambió / corrigió',
      'codeToInsert': 'Código para insertar',
      'copy': 'Copiar',
      'copied': 'Código copiado',
      'print': 'Escribir',
      'printHint': 'La posición del cursor aparecerá después de pulsar «Escribir».',
      'promptHint': 'Describa qué debe cambiarse en el código…',
      'addPhoto': 'Añadir captura',
      'send': 'Enviar',
      'ocr': 'OCR',
      'ocrQueued': 'Esperando OCR',
      'ocrProcessing': 'Reconociendo',
      'ocrDone': 'OCR listo',
      'ocrFailed': 'Error de OCR',
      'editOcr': 'Texto reconocido',
      'save': 'Guardar',
      'delete': 'Eliminar',
      'close': 'Cerrar',
      'settings': 'Ajustes',
      'interface': 'Interfaz',
      'interfaceLanguage': 'Idioma de la interfaz',
      'workstation': 'Estación de trabajo',
      'operatingSystem': 'Sistema operativo',
      'editor': 'Editor de código',
      'keyboardLayout': 'Distribución del teclado',
      'typing': 'Escritura',
      'typingSpeed': 'Velocidad: {value} car./s',
      'humanized': 'Ritmo de escritura natural',
      'api': 'API externa',
      'apiProvider': 'Formato de API',
      'apiBaseUrl': 'URL base de la API',
      'apiModel': 'Modelo',
      'apiKey': 'Clave de API',
      'apiTimeout': 'Tiempo de espera, segundos',
      'privacy': 'Privacidad',
      'corporateTerms': 'Dominios y nombres internos separados por comas',
      'device': 'Dispositivo ESP32-S3',
      'scan': 'Buscar dispositivos',
      'scanning': 'Buscando…',
      'connect': 'Conectar',
      'disconnect': 'Desconectar',
      'setupKey': 'Clave del dispositivo',
      'noDevices': 'No se encontraron dispositivos CodeKey',
      'deviceDiscoveryHint': 'El ESP32 permanece visible por Bluetooth mientras no haya un teléfono conectado. Se requiere la clave individual del dispositivo.',
      'usbIdentity': 'Identidad USB',
      'vid': 'VID (4 HEX)',
      'pid': 'PID (4 HEX)',
      'manufacturer': 'Fabricante',
      'productName': 'Nombre del teclado',
      'serialNumber': 'Número de serie',
      'applyUsb': 'Guardar en ESP32 y reiniciar',
      'usbWarning': 'Use solo VID/PID que esté autorizado a utilizar. El dispositivo USB se reconectará.',
      'saved': 'Ajustes guardados',
      'apiNotConfigured': 'Configure la URL, el modelo y la clave de API.',
      'requestRequired': 'Introduzca una solicitud.',
      'codeRequired': 'Añada al menos una captura y revise el texto OCR.',
      'processing': 'Procesando…',
      'privacyCheck': 'Comprobación de privacidad',
      'findings': 'Fragmentos potencialmente confidenciales: {count}',
      'maskedPayload': 'Texto exacto que se enviará',
      'systemInstruction': 'Instrucción del sistema',
      'userPayload': 'Solicitud y código',
      'rightsConfirm': 'Tengo autorización para enviar este fragmento a una API externa',
      'sendMasked': 'Enviar texto revisado',
      'backToEdit': 'Volver a editar',
      'noFindings': 'No se detectaron secretos ni datos personales evidentes. Esto no demuestra que el código no sea confidencial.',
      'cursorPlacement': 'Dónde colocar el cursor',
      'operation': 'Modo de inserción',
      'cursorReady': 'He colocado el cursor y preparado el editor',
      'saveAfter': 'Guardar después de escribir',
      'formatAfter': 'Formatear después de escribir',
      'startPrinting': 'Empezar a escribir',
      'printing': 'Escribiendo: {done} de {total}',
      'pause': 'Pausa',
      'resume': 'Continuar',
      'stop': 'Detener',
      'completed': 'Escritura terminada',
      'asciiError': 'El texto contiene caracteres no disponibles en la distribución elegida: {chars}',
      'deviceRequired': 'Conecte primero CodeKey al teléfono.',
      'warnings': 'Advertencias',
      'retry': 'Reintentar',
      'newRequest': 'Nueva solicitud',
      'operationInsert': 'Insertar en el cursor',
      'operationReplaceSelection': 'Reemplazar el texto seleccionado',
      'operationReplaceFile': 'Reemplazar el contenido del archivo',
      'operationNone': 'Solo recomendación',
      'error': 'Error',
      'cameraPermission': 'Se requiere acceso a la cámara.',
      'bluetoothPermission': 'Se requiere acceso a Bluetooth.',
      'deviceConfigSaved': 'Configuración guardada. ESP32 se reiniciará y USB se reconectará.',
      'hideApiKey': 'Ocultar clave',
      'showApiKey': 'Mostrar clave',
      'genericEditor': 'Editor genérico',
      'productPreset': 'Plantilla de nombre',
      'custom': 'Nombre propio',
      'technicalWarnings': 'Advertencias técnicas',
    },
    'zh': {
      'appName': 'CodeKey AI',
      'connected': '已连接',
      'disconnected': '未连接',
      'connecting': '连接中…',
      'responseFromLlm': 'LLM 回复',
      'whatChanged': '已完成 / 已修复',
      'codeToInsert': '待输入代码',
      'copy': '复制',
      'copied': '代码已复制',
      'print': '输入',
      'printHint': '点击“输入”后才会显示光标放置说明。',
      'promptHint': '请说明需要怎样修改代码…',
      'addPhoto': '添加截图',
      'send': '发送',
      'ocr': 'OCR',
      'ocrQueued': '等待 OCR',
      'ocrProcessing': '正在识别',
      'ocrDone': 'OCR 完成',
      'ocrFailed': 'OCR 失败',
      'editOcr': '识别文本',
      'save': '保存',
      'delete': '删除',
      'close': '关闭',
      'settings': '设置',
      'interface': '界面',
      'interfaceLanguage': '界面语言',
      'workstation': '工作站',
      'operatingSystem': '操作系统',
      'editor': '代码编辑器',
      'keyboardLayout': '键盘布局',
      'typing': '输入',
      'typingSpeed': '速度：{value} 字符/秒',
      'humanized': '自然输入节奏',
      'api': '外部 API',
      'apiProvider': 'API 格式',
      'apiBaseUrl': 'API 基础地址',
      'apiModel': '模型',
      'apiKey': 'API 密钥',
      'apiTimeout': '超时（秒）',
      'privacy': '隐私',
      'corporateTerms': '内部域名和名称，用逗号分隔',
      'device': 'ESP32-S3 设备',
      'scan': '查找设备',
      'scanning': '正在查找…',
      'connect': '连接',
      'disconnect': '断开',
      'setupKey': '设备密钥',
      'noDevices': '未找到 CodeKey 设备',
      'deviceDiscoveryHint': '未连接手机时，ESP32 会一直通过蓝牙保持可发现状态。连接时需要设备专用密钥。',
      'usbIdentity': 'USB 标识',
      'vid': 'VID（4 位十六进制）',
      'pid': 'PID（4 位十六进制）',
      'manufacturer': '制造商',
      'productName': '键盘名称',
      'serialNumber': '序列号',
      'applyUsb': '写入 ESP32 并重启',
      'usbWarning': '仅使用您有权使用的 VID/PID。修改后 USB 设备会重新连接。',
      'saved': '设置已保存',
      'apiNotConfigured': '请在设置中填写 API 地址、模型和密钥。',
      'requestRequired': '请输入用户请求。',
      'codeRequired': '请至少添加一张截图并检查 OCR 文本。',
      'processing': '处理中…',
      'privacyCheck': '隐私检查',
      'findings': '发现可能的机密片段：{count}',
      'maskedPayload': '将要发送的确切文本',
      'systemInstruction': '系统指令',
      'userPayload': '请求和代码',
      'rightsConfirm': '我有权将此片段发送到外部 API',
      'sendMasked': '发送已检查文本',
      'backToEdit': '返回编辑',
      'noFindings': '未检测到明显的密钥或个人数据，但这不能证明源代码不属于机密信息。',
      'cursorPlacement': '光标放置位置',
      'operation': '插入模式',
      'cursorReady': '我已放置光标并准备好编辑器',
      'saveAfter': '输入后保存',
      'formatAfter': '输入后格式化',
      'startPrinting': '开始输入',
      'printing': '输入中：{done}/{total}',
      'pause': '暂停',
      'resume': '继续',
      'stop': '停止',
      'completed': '输入完成',
      'asciiError': '文本包含当前键盘布局无法输入的字符：{chars}',
      'deviceRequired': '请先将 CodeKey 连接到手机。',
      'warnings': '警告',
      'retry': '重试',
      'newRequest': '新请求',
      'operationInsert': '在光标处插入',
      'operationReplaceSelection': '替换选中文本',
      'operationReplaceFile': '替换文件内容',
      'operationNone': '仅提供建议',
      'error': '错误',
      'cameraPermission': '拍摄屏幕需要相机权限。',
      'bluetoothPermission': '连接 CodeKey 需要蓝牙权限。',
      'deviceConfigSaved': '配置已保存。ESP32 将重启并重新连接 USB。',
      'hideApiKey': '隐藏密钥',
      'showApiKey': '显示密钥',
      'genericEditor': '通用编辑器',
      'productPreset': '名称模板',
      'custom': '自定义名称',
      'technicalWarnings': '技术警告',
    },
  };
}

class _CodeKeyLocalizationsDelegate
    extends LocalizationsDelegate<CodeKeyLocalizations> {
  const _CodeKeyLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) =>
      CodeKeyLocalizations.supportedLocales
          .any((supported) => supported.languageCode == locale.languageCode);

  @override
  Future<CodeKeyLocalizations> load(Locale locale) =>
      SynchronousFuture(CodeKeyLocalizations(locale));

  @override
  bool shouldReload(_CodeKeyLocalizationsDelegate old) => false;
}

extension CodeKeyStringsContext on BuildContext {
  CodeKeyLocalizations get strings => CodeKeyLocalizations.of(this);
}
